### ISSUE TITLE
No progressbar while interacting with owncloud server

### ISSUE THREAD

**Issue by MichaKersloot** [barrydegraaff/owncloud-zimlet#12]
While retreiving or sending a file from zimbra to owncloud, it could take some time to complete. There is no progressbar telling the user he should wait for the operation to complete.

**Comment by barrydegraaff** [comment]
Thanks, that's a good suggestion, I'll cook something up.

**Comment by barrydegraaff** [comment]
I have added a progress indication in the Attach from ownCloud dialog. I believe that is where the feedback is most usefull for the user. The second the progress indication is removed from the screen, you will see Draft Saved, and you see the attachments

Other cases like when dropping files to ownCloud are a bit more tricky, as this process is not blocking. This means that for JavaScript the routine is done, but the process is still firing DAV requests. The user can go and do something else in the meantime, like composing or reading mail. Only a window refresh or something like that would interrupt the process.

Adding a working progress indication would force me to rewrite the doDrop function for the most part, and it does not  add that much value, at least, thats what I think now.

Maybe you can take a look at the next version and see if the current fix is sufficient. Thanks.

**Comment by MichaKersloot** [comment]
Using the toast message is perfect. The progressbar is placed on the left top at the moment and not in the attachments area.

**Comment by barrydegraaff** [comment]
The Zimbra style is to show a progress bar in the attachment filename bubble while it works, I don't think there is a way to do that from the Zimlet framework. Or at least it will be very hard, so I think left top is good for now.

**Comment by MichaKersloot** [comment]
I'm not sure if you can target a specific div. Maybe id: skin_container_toast would be the correct target for this bubble?
