### ISSUE TITLE
Enhancement: allow sharing public link instead of file itself

### ISSUE THREAD

**Issue by maxxer** [barrydegraaff/owncloud-zimlet#13]
A cool feature of oC is the ability to share a public download link (like Dropbox does).
It would be cool to be able to insert a link to the download file instead of attaching the file itself.

**Comment by barrydegraaff** [comment]
I will see if I can get this to work:
https://doc.owncloud.org/server/6.0/developer_manual/core/ocs-share-api.html#create-a-new-share

**Comment by barrydegraaff** [comment]
Works when posted directly against ownCloud server, does not work via nginx proxy, says 

![2015-09-24-163953_1920x1200_scrot](https://cloud.githubusercontent.com/assets/4353213/10076271/f27abb76-62da-11e5-8a3a-31ba18577edd.png)


<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>

**Comment by barrydegraaff** [comment]
I don't think it is an nginx problem, most likely some security setting on the ownCloud server.

**Comment by barrydegraaff** [comment]
Dumping headers on the ownCloud server, shows that HTTP_AUTHORIZATION header is stripped by nginx.

**Comment by barrydegraaff** [comment]
Good news, sending the username and password in the .open method of xmlHttpRequests fixes this issue, and it works in Firefox, IE and Chrome:

var xmlHttp = new XMLHttpRequest();
xmlHttp.open("POST","/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares",true, tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_username'], tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_password']);
xmlHttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
xmlHttp.send("path=0.jpg&shareType=3&password=blaat&permissions=1");
xmlHttp.onload = function(e) 
{
console.log(xmlHttp);
}

So your share api can be build, where shall we integrate this...?

**Comment by barrydegraaff** [comment]
But with the above it will not work if the user is logged on to /owncloud using SSO... so we need a password in Zimbra for this solution.

**Comment by barrydegraaff** [comment]
The whole problem is that the HTTP cookie is not used and that nginx refuses to pass the HTTP_AUTHORIZATION that may be a ZImbra specific issue

**Comment by barrydegraaff** [comment]
It is a bit more complicated, it seems one can log on using HTTP Auth (JS and by hand) on 
/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares
That works as long as there is no other oC session (cookie)

As soon as there is another session, password is longer accepted, but sending request without it results in 401. Maybe we have to set the cookies that are returned in the successful request.

At least we need some more research here

**Comment by barrydegraaff** [comment]
maybe
http://stackoverflow.com/questions/2320110/how-do-i-set-a-cookie-header-with-xmlhttprequest-in-javascript

https://developer.mozilla.org/en-US/docs/Web/HTTP/Server-Side_Access_Control

Access-Control-Allow-Credentials

**Comment by barrydegraaff** [comment]
Also make sure I did not alter httpd config from defaults

**Comment by barrydegraaff** [comment]
Adding another proxy:
location /ocs/ {
   proxy_pass https://192.168.1.18/owncloud/ocs/;
}

then:
var xmlHttp = new XMLHttpRequest();
xmlHttp.open("POST","/ocs/v1.php/apps/files_sharing/api/v1/shares",true, tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_username'], tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_password']);
console.log(tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_password']);
xmlHttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
xmlHttp.send("path=0.jpg&shareType=3&password=blaat&permissions=1");
xmlHttp.onload = function(e) 
{
console.log(xmlHttp);
}

Seems to do the trick

**Comment by barrydegraaff** [comment]
2 days of joy, the problem is that XMLHttpRequest automatically sends session cookies to the ownCloud API.

But cookies are NOT a way of authenticating there... so this works as long as the user has not oC session open. This results that either the user gets a 401 when using the share API or when accessing other oC resources.

Some nobel price winner did design XMLHttpRequest without a way of influencing this behaviour... it appeears some browser (firefox) have non standard arguments that do the trick {mozAnon: true}:

We have to see if there is something like that in all browsers, if we ever want to get this working.

ownCloudZimlet.prototype.getShareLink =
function(uri, password) {
   var xmlHttp = new XMLHttpRequest({mozAnon: true});

   xmlHttp.open("POST","/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares",true, tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_username'], tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_password']);
   xmlHttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
   xmlHttp.setRequestHeader("Cookie", "", false); 
   xmlHttp.send("path="+uri+"&shareType=3&password="+password+"&permissions=1");
   xmlHttp.onload = function(e) 
   {
      var url = xmlHttp.response.match(/(<url>)([^]+)(<\/url>)/);
      var statuscode = xmlHttp.response.match(/(<statuscode>)([^]+)(<\/statuscode>)/);
      if((statuscode[2] == 100) && (url[2]))
      {
         url = url[2];
         console.log(xmlHttp.response);
         console.log(url);
         return url;
      }
   }
};

**Comment by barrydegraaff** [comment]
anon and mozanon appears to have not made it to a w3 standard and don't work in chrome,

This would work in chrome, but does not work in firefox:

   var xmlHttp = new XMLHttpRequest();

   xmlHttp.open("POST","https://192.168.1.18/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares",true, tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_username'], tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_password']);
   xmlHttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");
   xmlHttp.withCredentials = true;
   xmlHttp.setRequestHeader("Authorization", "Basic " + string.encodeBase64(tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_username'] + ":" + tk_barrydegraaff_owncloud_zimlet_HandlerObject.settings['owncloud_zimlet_password'])); 
   xmlHttp.send("path="+uri+"&shareType=3&password="+password+"&permissions=1");
   xmlHttp.onload = function(e) 
   {
      var url = xmlHttp.response.match(/(<url>)([^]+)(<\/url>)/);
      var statuscode = xmlHttp.response.match(/(<statuscode>)([^]+)(<\/statuscode>)/);
      if((statuscode[2] == 100) && (url[2]))
      {
         url = url[2];
         console.log(xmlHttp.response);
         console.log(url);
         return url;
      }
   }

After adding:
nano /etc/httpd/conf.d/owncloud.conf 

<Directory "/var/www/html/owncloud">

Header always set Access-Control-Allow-Origin "https://myzimbra.com"
Header always set Access-Control-Allow-Credentials "true"
Header add Access-Control-Allow-Headers "Authorization, origin, x-requested-with, content-type"
Header add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"

RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ blank.html [QSA,L]

    Options +FollowSymLinks
    AllowOverride None

**Comment by barrydegraaff** [comment]
I hate CORS

**Comment by barrydegraaff** [comment]
Adding a PHP wrapper script to work around all the above issues:
https://github.com/barrydegraaff/owncloud-zimlet/commit/c569f667fd1b9083295cbfe6e4f58059a2480a42
