### ISSUE TITLE
Enhancement: Automatically upload a file in Oc when hitting the max value

### ISSUE THREAD

**Issue by wolfyzvf** [barrydegraaff/owncloud-zimlet#14]
User case :
When you attach a document from your desktop to Zimbra and this one is too heavy, the file is automatically uploaded into Oc and a link is sent instead

It would be very nive to have this feature, lightweight emails :) !

**Comment by Dual-Boot** [comment]
:+1: 
And with a message asking the user if he wants to use ownCloud to do this.

**Comment by barrydegraaff** [comment]
Thanks for this suggestion, it is however to hard to build at this time, sorry.
