### ISSUE TITLE
Unable to Integrte  owncloud with zimbra

### ISSUE THREAD

**Issue by mbhanage** [barrydegraaff/owncloud-zimlet#22]
I have two different server one is owncloud and other is zimbra server. Please tell me the changes I need to config_template.xml

<zimletConfig name="tk_barrydegraaff_owncloud_zimlet" version="1.0">
    <global>
        <property name="proxy_location">https://192.168.10.88/owncloud</property>
        <property name="dav_path">/remote.php/webdav/</property>
        <property name="disable_link_sharing">false</property>
        <property name="disable_password_storing">false</property>
    </global>
</zimletConfig>

My owncloud is working fine through web but not able with zimbra owncloud ziml
![ownclouderror](https://cloud.githubusercontent.com/assets/14975140/10277235/3e99ef78-6b72-11e5-89a1-eff36e53bc51.JPG)
et
When I put these settings then

**Comment by barrydegraaff** [comment]
You should NOT type the full domain ONLY /owncloud

https://192.168.10.88/owncloud should not be in the global config xml

Please read the manual:
https://github.com/barrydegraaff/owncloud-zimlet/blob/master/README.md

**Comment by mbhanage** [comment]
Dear Barry,

Thanks for very prompt reply. Please guide me how to integrate zimbra with
owncloud because I have two different server one is owncloud and other is
zimbra.

Regards,

Mangesh Bhanage (India)

**Comment by mbhanage** [comment]
Dear Barry,

I have single zimbra server and nginx is not configure is it necessary nginx required to configure owncloud zimlet.

**Comment by barrydegraaff** [comment]
** Please ** read :
https://github.com/barrydegraaff/owncloud-zimlet/blob/master/README.md

readme.md describes EXACTLY what you want

**Comment by barrydegraaff** [comment]
a proxy server is required, YES

**Comment by barrydegraaff** [comment]
Also, please note, from Zimbra 8.7 and above, installing Zimbra Proxy will be required by Zimbra!
