### ISSUE TITLE
Enable link sharing

### ISSUE THREAD

**Issue by bachkhoabk47** [barrydegraaff/owncloud-zimlet#24]
Dear author, Barrydegraaff!
I'm Tan and I come from Vietnam!
You know, I follow your tutorial and when I met step how to enable link sharing, I think, I met wrong!
That's main reason why I could not share link file in message!
So can you tell me more detail about that?
PS: I used Zimbra 8.5.1 (not 8.6 version like you) but I can attach the file by using owncloud.
1. Do I need to upgrade to Zimbra version 8.6?
2. About the below line:
$url = "https://".$_SERVER['SERVER_NAME']."/".$_GET['proxy_location']."/ocs/v1.php/apps/files_sharing/api/v1/shares";

Thank you so much! :)

**Comment by barrydegraaff** [comment]
Did you do this steps on your ownCloud server:

[root@owncloud1 ~]# cd /var/www/html/owncloud/ocs/
[root@owncloud1 ~]# rm -Rf zcs.php
[root@owncloud1 ~]# wget https://raw.githubusercontent.com/barrydegraaff/owncloud-zimlet/master/php/zcs.php

Then see if it works:
https://your-zimbra-domain-here/owncloud/ocs/zcs.php?path=havesession

The answer should be true or false, it should not say 404 or whatever

**Comment by bachkhoabk47** [comment]
Hi!
Thanks for your feedback!
And I see "false" word in the brower.
What shoud I do?

**Comment by barrydegraaff** [comment]
Do you see ANYTHING appear in your compose window?

Most of the times if ownCloud integration is broken you will see:
Use AIYGcCYvNk for:�
[then nothing]

If all works you will see:
Use AIYGcCYvNk for:�
https://owncloud1.hivos.nl/owncloud/index.php/s/jXQpMzZuihGCrf

If Zimbra is failing or browser fail you will see nothing.

Do you see ANYTHING? Then it may indeed be a 8.5 issue.

**Comment by bachkhoabk47** [comment]
Yeah!
You know, nothing is appeared after I chose attach share as link! :(

**Comment by barrydegraaff** [comment]
Most likely the getHtmlEditor was not there in 8.5, press F12 in most browsers, so the developers console is opened, in the tab Console, you should see some unhandled exceptions.
var content = composeView.getHtmlEditor().getContent();

**Comment by barrydegraaff** [comment]
I think I saw this before: https://github.com/barrydegraaff/pgp-zimlet/issues/82
https://github.com/barrydegraaff/pgp-zimlet/issues/49

**Comment by bachkhoabk47** [comment]
Hi! Thank you, Barrydegraaff!
I will try to fix the issue, and if could not, I will ask you more ! :)

**Comment by bachkhoabk47** [comment]
Hi, Barrydegraaff. I was success to integrate owncloud with Zimbra version 8.6 with share link and attach file functions.
Thank alot. :)

**Comment by barrydegraaff** [comment]
Nice, a success story! Thanks!
________________________________

**Comment by barrydegraaff** [comment]
So conclusion, ownCloud Zimlet does not work with 8.5.x

**Comment by vitorrolo** [comment]
Hello,
I have the exact same problem as bachkhoabk47, with Zimbra 8.6.
Can you tell what was the problem, and how was it solved ?

Thank you very much.
Vitor

**Comment by barrydegraaff** [comment]
Don't know, open a new issue and describe your exact problem
