### ISSUE TITLE
Integrate Owncloud and Zimbra running on Centos 6.6

### ISSUE THREAD

**Issue by bachkhoabk47** [barrydegraaff/owncloud-zimlet#27]
<h4>Dear authors!</h4>

You know, I got the success when integrating Owncloud and Zimbra 8.6 running on Centos 7.
But now, I try to integrate Owncloud with Zimbra 8.6 running on Centos 6.6, and then I got the error bellow.

So please tell me that your owncloud-zimlet was supported to Zimbra running on Centos 6 or not?
Thank you so much!

<h6>
method:	[unknown]
msg:	permission denied: can not modify options
code:	service.PERM_DENIED
detail:	soap:Sender
trace:	qtp509886383-320:https://119.15.167.204:8443/service/soap/ModifyPropertiesRequest:1446102358079:aa36db49c43745cf
request:	
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><context xmlns="urn:zimbra"><userAgent name="ZimbraWebClient - GC45.2 (Win)" version="8.6.0_GA_1153"/><session id="116"/><account by="name">demo1@gov-mail.com</account><format type="js"/><csrfToken>0_563ab00feaa401d35ce96402047a7dec232b8712</csrfToken></context></soap:Header><soap:Body><ModifyPropertiesRequest xmlns="urn:zimbraAccount"><prop zimlet="tk_barrydegraaff_owncloud_zimlet" name="owncloud_zimlet_username"></prop><prop zimlet="tk_barrydegraaff_owncloud_zimlet" name="owncloud_zimlet_password"></prop><prop zimlet="tk_barrydegraaff_owncloud_zimlet" name="owncloud_zimlet_default_folder">Zimbra emails</prop><prop zimlet="tk_barrydegraaff_owncloud_zimlet" name="owncloud_zimlet_store_pass">false</prop></ModifyPropertiesRequest></soap:Body></soap:Envelope>
</h6>

**Comment by barrydegraaff** [comment]
The Zimlet is known to work on CentOS 6 and 7 using ZCS 8.6

It looks like maybe you have used the 'view mail' option in the admin panel, or some other misconfiguration. As you try to store and LDAP value over port 8443, that may NOT be correct.

Try to log on directly over port 443, and try again.
