### ISSUE TITLE
Wrong character coding folder names and plain/text files

### ISSUE THREAD

**Issue by vonanstet** [barrydegraaff/owncloud-zimlet#28]
Hi Barry!

First, thanks for the useful zimlet. We use it in environment with a Hungarian language. 
There are some special characters for us. For example: áéüóűőúí. 
If  we would like to attach it from owncloud, then the library's names wrong displays it. 
For example: Ajánlat directory -> AjA~nlat , or  Telepítés -> TelepA~tA%.

Can you help me, what is the issue?

Thanks, George

**Comment by barrydegraaff** [comment]
Thanks for reporting. it appears to work in file names but not in folder names... it will be fixed for sure.

Right now we are rewriting the Zimlet in  https://github.com/ZeXtras/owncloud-zimlet/commits/soapService

So maybe it will end up in that version, otherwise I will fix it soon in this version.

**Comment by barrydegraaff** [comment]
I fixed the folder names, you can install the new version by using : 

      [root@myzimbra ~]# yum install -y git 
      [root@myzimbra ~]# apt-get -y install git
      [root@myzimbra ~]# cd ~
      [root@myzimbra ~]# rm owncloud-zimlet -Rf
      [root@myzimbra ~]# git clone https://github.com/barrydegraaff/owncloud-zimlet
      [root@myzimbra ~]# cd owncloud-zimlet

      [root@myzimbra owncloud-zimlet]# chmod +rx install-dev.sh
      [root@myzimbra owncloud-zimlet]# ./install-dev.sh
      [root@myzimbra owncloud-zimlet]# su zimbra
      [zimbra@myzimbra owncloud-zimlet] zmprov mc default zimbraPrefZimletTreeOpen TRUE
      [zimbra@myzimbra owncloud-zimlet] zmcontrol restart

However it appears plain text files with UTF are also not attached correctly, so reopen this one

**Comment by barrydegraaff** [comment]
That one appears to be a bug in Zimbra, I cannot upload a plain/text message with UTF8 characters in it and then when I click on it in Zimbra, it is not served back to me with UTF-8 content-type.

However, if I download the file and view it in my OS, it works fine.

**Comment by barrydegraaff** [comment]
No, reading an utf-8 text file in firefox and chrome fails, so I guess, not a Zimbra issue.
