### ISSUE TITLE
Zimbra Proxy location

### ISSUE THREAD

**Issue by duke8804** [barrydegraaff/owncloud-zimlet#29]
I followed the directions as you recommend, but when i change the file /opt/zimbra/conf/nginx/templates/nginx.conf.web.https.default.template. 

I restart the proxy service and get the following error
zimbra@mail:~$ zmproxyctl restart
Stopping nginx...done.
Starting nginx...nginx: [emerg] "location" directive is not allowed here in /opt/zimbra/conf/nginx/includes/nginx.conf.web.https.default:467

I am using ubuntu 14.04 with Zimbra version 8.6.0

**Comment by barrydegraaff** [comment]
Did you add your location block ABOVE the final }  ?

**Comment by duke8804** [comment]
Thank you for the quick reply.

That is what my issue was. Thank you. 

Not sure if i should create a new issue or not, but i am unable to find the zimlet in the Admin console. I would like to be able to disable it in the global settings and only enable for certain users during testing.

**Comment by barrydegraaff** [comment]
Sorry, that does NOT work when installed in _dev mode.

**Comment by duke8804** [comment]
Ok thank you for your answers. 

This is a great add-on and i hope you continue to develop it. 

If you ever need a test bed please let me know i will be willing to help all i can.
