### ISSUE TITLE
Not able to share a link

### ISSUE THREAD

**Issue by duke8804** [barrydegraaff/owncloud-zimlet#30]
Maybe jsut a permissions issue with Owncloud, but when I am want to attach and share a link to an email it is not adding in the link. 

I am able to attach a file directly to the email just not create the link.

**Comment by duke8804** [comment]
Refused to set unsafe header "Accept-Encoding"DavClient._getRequest @ davclient.js?v=141215154045&language=en&country=US&debug=1:481DavClient.PROPFIND @ davclient.js?v=141215154045&language=en&country=US&debug=1:391ownCloudTabView._createHtml1 @ tk_barrydegraaff_owncloud_zimlet.js?v=141215154045&language=en&country=US&debug=1:703ownCloudTabView @ tk_barrydegraaff_owncloud_zimlet.js?v=141215154045&language=en&country=US&debug=1:650xmlHttp.onload @ tk_barrydegraaff_owncloud_zimlet.js?v=141215154045&language=en&country=US&debug=1:207

That is the error i am getting in Chrome

**Comment by duke8804** [comment]
This is the Error i get in IE 11

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337

**Comment by barrydegraaff** [comment]
Could you please read the readme.md file. You need to install zcs.php
________________________________

**Comment by duke8804** [comment]
I have installed the zcs.php file. 

I read and re-read the readme.md multiple time making sure i did not over look something like i did the first time.  

I attached a screenshot of my ssh session where i redid the zcs.php file just a minute ago.

![capture](https://cloud.githubusercontent.com/assets/12399785/10848694/2e3b93fc-7eeb-11e5-808f-452d2229a744.PNG)

**Comment by duke8804** [comment]
When i go to 

https://mydomain/owncloud/ocs/zcs.php?path=havesession

I get a page that just says false.

I was looking at the zcs.php and not sure if this helps or not but the line

$url = "https://".$_SERVER['SERVER_NAME']."/".$_GET['proxy_location']."/ocs/v1.php/apps/files_sharing/api/v1/shares"; 

thers is a path to /ocs/v1.php 

The path /apps/files_sharing/api/v1  does not exsit. 

In my API folder i have "local.php" and "server2server.php"

I am running owncloud 8.1.3

**Comment by barrydegraaff** [comment]
Sounds like you installed zcs.php correctly, please try and share a file or folder with a public link in the ownCloud gui. Then that share should show up here:
https://YOUR_SERVER/owncloud/ocs/zcs.php?proxy_location=/owncloud&zcsuser=YOUR_USER_NAME&zcspass=YOUR_PASSWORD&path=getshares

What is the output?

This should prompt for a username and password (http auth) but it should NOT work in your browser as it expects a POST request: 
https://localhost/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares

This thing:  /apps/files_sharing/api/v1  is something that is a redirection in ownCloud, there is no path there on your filesystem.

**Comment by duke8804** [comment]
When i go to the requested site nothing happens. I get a blank page. I verified that the file is shared publicly by accessing the share link from a separate network not logged in.

**Comment by barrydegraaff** [comment]
Do you have PHP curl installed? Remove the line with error_reporting try again.

Also check the PHP error log
________________________________

**Comment by barrydegraaff** [comment]
SElinux or firewall in the way?
________________________________

**Comment by duke8804** [comment]
Firewall has ports 80 and 443 open. Selinux is not enabled or installed at all.  Php curl is installed. I will check the PHP log in a moment and let you know about that.
![capture](https://cloud.githubusercontent.com/assets/12399785/10885172/8a55e950-8141-11e5-8a1e-c5c1f0fdea45.PNG)

**Comment by duke8804** [comment]
I had 0 errors appear in my php_errors.log file

**Comment by barrydegraaff** [comment]
Well I don't know what the problem is, maybe you work with additional proxies

  
  


or different domain/hostnames.
I guess this is where the free support ends. You can disable the link sharing feature:In your install:nano /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/config_template.xml<property name="disable_link_sharing">true</property>Alternatively you can wait for the next release, that probably won't require the zcs.php hack

**Comment by duke8804** [comment]
Ok fair enough. Once you release the next version i will give that a go. 

I do appreciate that you have created this. I have been looking for something like this for a long time. 

Once I am able to use the product with at least the link creation working I am planning on send a payment to the paypal account. Like i said this add-in is great and I will support you once I am able to get that feature working correctly. I will let you know if i make any progress on getting it working.
