### ISSUE TITLE
Zimbra & Owncloud on different domain

### ISSUE THREAD

**Issue by BarBaar44** [barrydegraaff/owncloud-zimlet#31]
Hi,

Interesting project!

I run a server that has both Owncloud and Zimbra installed. However, they both run on different subdomains:
- owncloud.yourdomain.com
- zimbra.yourdomain.com

Both are (of course) installed in different webroot, and both are served with Apache (CentOS 7). Zimbra is internally being proxied over http.

What would be the correct configuration for this?

Regards,

Bart

**Comment by barrydegraaff** [comment]
Hello BarBaar44,

You should configure your ownCloud as a reverse proxy in apache like:

   <Location /owncloud>
      ProxyPass https://owncloud.yourdomain.com/owncloud
      #maybe no need for this: ProxyPassreverse https://owncloud.yourdomain.com/owncloud
   </Location>

And then it all the same as in the README.md.

Regards, Barry
