### ISSUE TITLE
Problem double autentication

### ISSUE THREAD

**Issue by newoneitalia** [barrydegraaff/owncloud-zimlet#32]
Hi, sorry for my poor english...I have configurated your Zimlet, all working fine....thanks for this Zimlet...only a little problem...I have insert username and password for owncloud in zimlet in zimbra, this working , If I click in tab owncloud working all....but If I send email and choice one file in owncloud in attachment this required another user and password , if click cancels insert attachment and message is saved in draft...
where did I go wrong ? thanks for your support
Cal.

**Comment by barrydegraaff** [comment]
Please make a screenshot of the double authentication dialog.

**Comment by barrydegraaff** [comment]
also show the configuration of your:
1. Preferences in Zimlet (web gui)
2. Contents of proxy configuration
3. Contents of config_template.xml

**Comment by newoneitalia** [comment]
Hi, this is screenshot...This happens when choice file and attach in email...
![2015-11-17_0805](https://cloud.githubusercontent.com/assets/15878932/11204835/f3603f0a-8d02-11e5-924f-5e96dd498878.png)
 after If click cancel have file in attachment and email ready for sending....
![2015-11-17_0805_001](https://cloud.githubusercontent.com/assets/15878932/11204852/0e09556c-8d03-11e5-9e50-f06b68c8ecab.png)

**Comment by newoneitalia** [comment]
![2015-11-17_0837](https://cloud.githubusercontent.com/assets/15878932/11205246/83828d38-8d06-11e5-8ae6-3ab17479856e.png)

2. location /owncloud/ {
    proxy_pass https://ams02.owndrive.it/owncloud/;
}

**Comment by barrydegraaff** [comment]
The pop-up is a result of a http-auth session that is not correct, it looks like it specifically wants togo to port 443.
That means you may have started zimbra from a different port, or something is redirectingimproperly.
Try:

  
  


location /owncloud/ { proxy_pass https://ams02.owndrive.it:443/owncloud/;

**Comment by newoneitalia** [comment]
Hi , I have changed as your advice, but have the same result...

**Comment by barrydegraaff** [comment]
maybe send a test owncloud account to info@barrydegraaff.tk

**Comment by barrydegraaff** [comment]
fixed by a fresh install of ownCloud.
