### ISSUE TITLE
Find out how to require zimbra auth before access to proxy oC is granted

### ISSUE THREAD

**Issue by barrydegraaff** [barrydegraaff/owncloud-zimlet#7]
Add to the bottom of /opt/zimbra/conf/nginx/templates/nginx.conf.web.https.default.template before the final }
    location /owncloud/ {
        proxy_pass https://owncloud.example.com/owncloud/;
    }

Find out how to require zimbra auth before access to proxy oC is granted, since only oc login-page may not be desirable for all corporations

**Comment by barrydegraaff** [comment]
Hard part here is that the login cookies and all seem to be handled by jetty and not nginx, so not sure if we can access this from nginx

**Comment by manens** [comment]
as for #1, this can be resolved with Zimbra Zimlet proxy, no ?

**Comment by barrydegraaff** [comment]
This is fixed by 
https://github.com/barrydegraaff/owncloud-zimlet/wiki/Zimbra-and-ownCloud-Single-Sign-On-SSO
