### ISSUE TITLE
Find out how to support global configuration to allow custom locations and such

### ISSUE THREAD

**Issue by barrydegraaff** [barrydegraaff/owncloud-zimlet#8]
Maybe a COS setting, so we don't need SysAdmins to alter the code like:

Now open /tmp/owncloud-zimlet/tk_barrydegraaff_owncloud_zimlet/tk_barrydegraaff_owncloud_zimlet.js and look for the comment: 'custom location set here' after this comment you find a line where you should replace /owncloud with /oc or whatever your location is.

**Comment by barrydegraaff** [comment]
@maxxer this one is for your usecase

**Comment by manens** [comment]
Hi barry,

Do you want to use config_template or something else ? 
https://wiki.zimbra.com/wiki/Zimlet_Developers_Guide:Developing_Zimlets#Zimlet_Configuration_File

Best regards,

**Comment by barrydegraaff** [comment]
I looked into it a few times before, and maybe I shot it down cause it does not work when the Zimlet is install from the _dev folder.

Also I prefer something that can be done via zmprov/cli or the admin web interface.

But I will look into the xml again.

**Comment by manens** [comment]
With the config template, you can deploy the configuration with zmzimletctl  : 
https://wiki.zimbra.com/wiki/CLI_zmzimletctl

zmzimletctl configure config_template.xml

That mean you don't need to deploy the zimlet with the configuration, you can configure after.

**Comment by barrydegraaff** [comment]
I just tested it, and it works also from _dev so this one is going to be implemented soon
